targets:
  $default:
    builders:
      json_serializable:
        options:
          # Cấu hình JSON serialization
          explicit_to_json: true
          field_rename: snake
          checked: true

      freezed:
        enabled: true
